version: '3'

tasks:
  clean:
    desc: clean up
    cmds:
      - task: clean-agents
      - task: clean-server

  lint:
    desc: lint-agent
    env:
      PYTHONPATH: "./agents/nyra_packages/system/nyra_runtime_python/lib:./agents/nyra_packages/system/nyra_runtime_python/interface:./agents/nyra_packages/system/nyra_ai_base/interface"
    cmds:
      - ./agents/scripts/pylint.sh

  install-tools:
    desc: install tools
    cmds:
      - pip install pylint

  build:
    desc: build
    cmds:
      - task: build-agent
      - task: build-server

  use:
    desc: use agent, default 'agents/examples/default'
    vars:
      AGENT: '{{.AGENT| default "agents/examples/default"}}'
    cmds:
      - ln -sf {{.USER_WORKING_DIR}}/{{.AGENT}}/manifest.json ./agents/
      - ln -sf {{.USER_WORKING_DIR}}/{{.AGENT}}/property.json ./agents/
      - task: build

  run-server:
    desc: run backend http server
    cmds:
      - source .env && /app/server/bin/api

  run-gd-server:
    desc: run graph designer dev http server
    dir: ./agents
    cmds:
      - tman designer

  run:
    desc: run servers
    deps:
      - task: run-server
      - task: run-gd-server

  build-agent:
    desc: build agent
    dir: ./agents
    internal: true
    cmds:
      - ./scripts/install_deps_and_build.sh linux x64 && mv bin/main bin/worker

  build-server:
    desc: build server
    dir: ./server
    cmds:
      - go mod tidy && go mod download && go build -o bin/api main.go

  clean-agents:
    desc: clean up agents
    dir: ./agents
    internal: true
    cmds:
      - rm -rf manifest.json property.json manifest-lock.json bin/main bin/worker out .release nyra_packages/system/nyra_runtime* nyra_packages/system/agora_rtc_sdk nyra_packages/system/azure_speech_sdk nyra_packages/system/nlohmann_json nyra_packages/extension/agora_rtc nyra_packages/extension/agora_rtm nyra_packages/extension/agora_sess_ctrl nyra_packages/extension/azure_tts nyra_packages/extension/py_init_extension_cpp

  clean-server:
    desc: clean up server
    dir: ./server
    internal: true
    cmds:
      - rm -rf bin
